### ISSUE TITLE
generatingSystem does not have label in XML

### ISSUE THREAD

**Issue by mcNisse** [diggsweden/sdk-docs#4]
### Contact Details (Optional)

johan.erlands@idainfront.se

### What happened?

The JSON schema contains attributes that does not exist in XML schema.

### Steps To Reproduce

Look in the specifications and compare.

### What did you expect?

Schemas should match

### Screenshots (Optional)

XML
```
			<xs:element name="generatingSystem" type="tns:IIType"
				minOccurs="0" maxOccurs="1">
			</xs:element>
	<xs:complexType name="IIType">
		<xs:sequence>
			<xs:element name="root" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="extension" type="xs:string" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
```
JSON
```
    generatingSystemDef:
      description:
        Identifierare för systemet som skapade/genererade meddelandet. Id
        kan användas för felsökning/support.
      type: object
      properties:
        root:
          type: string
        extension:
          type: string
        label:
            type: string
```
