### ISSUE TITLE
SDK-API: Filter definition is wrong

### ISSUE THREAD

**Issue by mcNisse** [diggsweden/sdk-docs#9]
### Contact Details (Optional)

johan.erlands@idainfront.se

### What happened?

When using generated service stubs you get an list of filters. The list is empty untill you write `?filter=bar&filter=foo`. 
This is not the way it is described in the pdf. Where you say that `?filter[recipientAttention.subOrganization.extension]=org.funk1` should be used.

This is fixed by saying that filter is an object with properties. As a bunus you will describe all filter conditions.
```
        - in: query
          name: filter
          required: true
          description: "The filter query parameter family is reserved to be used as the basis for any filtering of strategy. ?Filter[attribute]=value"
          example: '?filter[recipientAttention.subOrganization.extension]=sdk:inkorg001:0203:inera.se'
          schema:
            type: object
            properties:
              recipientAttention.subOrganization.extension:
                type: string
              senderAttention.subOrganization.extension:
                type: string
          ...
          style: deepObject
          explode: true
```

### Steps To Reproduce

- Generate code.
- Deploy code.

### What did you expect?

Filter is reaching the stubs.
